"use client";
import { useEffect, useState } from "react";
import { nombresRol, esRolUsuario, type RolUsuario } from "@/lib/auth/roles";
import { createClient } from "@/lib/supabase/client";

export default function Configuracion() {
  const [correo,setCorreo]=useState(""); const [nombre,setNombre]=useState(""); const [rol,setRol]=useState<RolUsuario|null>(null); const [mensaje,setMensaje]=useState(""); const [error,setError]=useState(""); const [cargando,setCargando]=useState(true); const [guardando,setGuardando]=useState(false);
  useEffect(()=>{let activo=true;async function cargar(){const supabase=createClient();const {data,error}=await supabase.auth.getUser();if(!activo)return;if(error||!data.user){setError(error?.message??"No hay sesión activa.");setCargando(false);return;}setCorreo(data.user.email??"");const {data:perfil,error:errorPerfil}=await supabase.from("perfiles").select("nombre, rol").eq("id",data.user.id).single();if(!activo)return;if(errorPerfil){setError(errorPerfil.message);}else{setNombre(perfil?.nombre??"");setRol(esRolUsuario(perfil?.rol)?perfil.rol:null);}setCargando(false);}void cargar();return()=>{activo=false}},[]);
  async function guardar(){if(guardando)return;setGuardando(true);setError("");setMensaje("");const supabase=createClient();const {data}=await supabase.auth.getUser();if(!data.user){setError("No hay sesión activa.");setGuardando(false);return;}const {error}=await supabase.from("perfiles").update({nombre:nombre.trim()||null}).eq("id",data.user.id);if(error)setError(error.message);else setMensaje("Perfil actualizado correctamente.");setGuardando(false);}
  return <main className="bg-slate-950 p-5 text-white md:p-8"><div className="mx-auto max-w-3xl"><section className="space-y-5 rounded-2xl border border-slate-800 bg-slate-900 p-6 md:p-8">{error&&<div className="rounded-xl border border-red-500/40 bg-red-500/10 p-4 text-red-300">{error}</div>}{mensaje&&<div className="rounded-xl border border-green-500/40 bg-green-500/10 p-4 text-green-300">{mensaje}</div>}{cargando?<div className="py-12 text-center text-slate-400">Cargando configuración...</div>:<><label className="block"><span className="mb-2 block font-semibold">Correo</span><input disabled value={correo} className="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-slate-400"/></label><label className="block"><span className="mb-2 block font-semibold">Nombre visible</span><input value={nombre} onChange={(e)=>setNombre(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 outline-none focus:border-green-500"/></label><label className="block"><span className="mb-2 block font-semibold">Rol asignado</span><input disabled value={rol?nombresRol[rol]:"Sin rol válido"} className="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-slate-400"/><span className="mt-2 block text-xs text-slate-500">Por seguridad, el rol solo se cambia desde la administración de Supabase.</span></label><button onClick={()=>void guardar()} disabled={guardando} className="w-full rounded-xl bg-green-600 px-5 py-3 font-bold disabled:opacity-60">{guardando?"Guardando...":"Guardar perfil"}</button></>}</section></div></main>;
}
